version: "3.9"

services:
  web:
    build: .
    command: python ./manage.py
    restart: always
    volumes:
      - .:/src
    ports:
      - 8005:8005
    depends_on:
      - db
    env_file:
      - .env
  
  sec:
    build: .
    command: python ./security/__main__.py
    restart: always
    ports:
      - 8066:8066

  db:
    image: postgres:13
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 



volumes:
  postgres_data:
